#!/usr/bin/env bash
set -euo pipefail

function quoted_print() {
    python -c 'import pipes; import sys; print(" ".join(pipes.quote(arg) for arg in sys.argv[1:]))' "$@"
}

function call() {
    if [[ ${DRY_RUN:-} ]]; then
        echo "${PS4}"$(quoted_print "$@")
    else
        { set -x; } 2>/dev/null
        "$@"
        { set +x; } 2>/dev/null
    fi
}

PREBUILT_PATH=`pwd`/vendor/prebuilt/macosx-x86_64/swift-syntax-test
call cd -P vendor/swift-source
# call swift/utils/update-checkout

if [ -n "${DEBUG:-}" ]; then
  call swift/utils/build-script --skip-build-swift
  call cd build/Ninja-DebugAssert/swift-macosx-x86_64
else
  call swift/utils/build-script --skip-build-swift --release-debuginfo
  call cd build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64
fi

call ninja swift-syntax-test
call cp bin/swift-syntax-test "$PREBUILT_PATH"
